spring:
  application:
    name: gmm
  datasource:
    url: jdbc:p6spy:mariadb://localhost:3306/gmm
    username: stock
    password: stock1234
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: /api
logging:
  level:
    p6spy: INFO
