spring:
  application:
    name: gmm
  datasource:
    url: jdbc:p6spy:h2:mem:gmm
    username: sa
    password:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    defer-datasource-initialization: true
server:
  servlet:
    context-path: /api
logging:
  level:
    p6spy: INFO
